### PR TITLE
Updated the systemd service to require acpid

### PR DESCRIPTION
**Pull request by PlasmaPower**
Not tested.

### CODE REVIEW

**Comment by amonakov** [comment]
Why? Bumblebee does no interaction with apcid, let alone depend on it.

**Comment by PlasmaPower** [comment]
Apparently if it is not running, you will get the error `primus: fatal: Bumblebee daemon reported: error: [XORG] (EE) systemd-logind: failed to get session: PID 4036 does not belong to any known session`. See the last comment on #600.

**Comment by intelfx** [comment]
@PlasmaPower: This is a completely unrelated error.
(Something should probably be fixed to not treat this as an error. Xorg, probably.)

**Comment by Lekensteyn** [comment]
This message is harmless, it was ignored in b506a03abab85bc202109f8eeda5c337ee956935 (which is not in a released version of Bumblebee though).

**Comment by PlasmaPower** [comment]
Okay. Thanks for the info.

**Pull request closed without merging**
